#pragma once
#include <juce_gui_basics/juce_gui_basics.h>
#include <cmath>
#include "BinaryData.h"
class FreakLookAndFeel : public juce::LookAndFeel_V4 {
public:
	static const juce::Colour mint, cream, bezel, rust, inkDark;
	FreakLookAndFeel() { setColour(juce::GroupComponent::textColourId, cream);setColour(juce::Slider::textBoxTextColourId, cream);setColour(juce::Slider::textBoxBackgroundColourId, juce::Colours::transparentBlack);setColour(juce::Slider::textBoxOutlineColourId, juce::Colours::transparentBlack);setColour(juce::TextEditor::textColourId, cream);setColour(juce::TextEditor::backgroundColourId, juce::Colours::transparentBlack);setColour(juce::TextEditor::outlineColourId, juce::Colours::transparentBlack);setColour(juce::Label::textColourId, cream);setColour(juce::Label::backgroundColourId, juce::Colours::transparentBlack);setColour(juce::Label::outlineColourId, juce::Colours::transparentBlack);setColour(juce::ToggleButton::textColourId, cream); }
	void setPointerJitter(float amount) noexcept { pointerJitter = juce::jlimit(0.0f, 0.55f, amount); } void setAnimationPhase(float phase) noexcept { animationPhase = phase; }
	void drawRotarySlider(juce::Graphics& g, int x, int y, int w, int h, float pos, float start, float end, juce::Slider& slider) override { auto area = juce::Rectangle<float>((float)x, (float)y, (float)w, (float)h).reduced(4.0f);const float side = juce::jmin(area.getWidth(), area.getHeight());auto knob = juce::Rectangle<float>(side, side).withCentre(area.getCentre());const auto centre = knob.getCentre();const float radius = side * .5f;const float angle = start + juce::jlimit(0.0f, 1.0f, pos) * (end - start);auto image = knobImageFor(slider);g.setColour(juce::Colours::black.withAlpha(.32f));g.fillEllipse(knob.translated(1.0f, 1.5f));if (image.isValid())g.drawImageWithin(image, (int)knob.getX(), (int)knob.getY(), (int)knob.getWidth(), (int)knob.getHeight(), juce::RectanglePlacement::centred, false);else { g.setColour(juce::Colour(0xff272326));g.fillEllipse(knob); }g.setColour(juce::Colour(0xff080709).withAlpha(.38f));g.drawEllipse(knob.reduced(radius * .025f), 1.0f);auto arcBounds = knob.reduced(radius * .075f);juce::Path arc;arc.addCentredArc(arcBounds.getCentreX(), arcBounds.getCentreY(), arcBounds.getWidth() * .5f, arcBounds.getHeight() * .5f, 0.0f, start, angle, true);g.setColour(juce::Colour(0xff753940).withAlpha(.72f));g.strokePath(arc, juce::PathStrokeType(1.35f));auto core = knob.reduced(radius * .38f);g.setColour(juce::Colour(0xff08080a).withAlpha(.92f));g.fillEllipse(core);g.setColour(juce::Colour(0xffb9a98f).withAlpha(.30f));g.drawEllipse(core, .9f);const float jitter = pointerJitter * std::sin(animationPhase * 1.73f + centre.getX() * .071f + centre.getY() * .113f);juce::Path pupil;pupil.addRoundedRectangle(-1.15f, -radius * .67f, 2.3f, radius * .45f, .7f);pupil.applyTransform(juce::AffineTransform::rotation(angle).translated(centre.translated(jitter, -jitter * .5f)));g.setColour(cream.withAlpha(.94f));g.fillPath(pupil);auto eye = core.reduced(core.getWidth() * .32f);g.setColour(juce::Colour(0xff24161a).withAlpha(.88f));g.fillEllipse(eye); }
	void drawToggleButton(juce::Graphics& g, juce::ToggleButton& button, bool over, bool down) override { auto b = button.getLocalBounds().toFloat().reduced(1.0f);float height = juce::jmin(b.getHeight(), 22.0f);auto track = b.withHeight(height).withY(b.getCentreY() - height * .5f).withWidth(42.0f);bool page = button.getButtonText().isEmpty();auto colour = page ? juce::Colour(0xff71313d) : (button.getToggleState() ? juce::Colour(0xff4a2d32) : juce::Colour(0xff1b1b1d));if (over)colour = colour.brighter(.08f);if (down)colour = colour.darker(.12f);g.setColour(juce::Colour(0xff080809));g.fillRoundedRectangle(track.translated(1, 1.5f), height * .5f);g.setColour(colour);g.fillRoundedRectangle(track, height * .5f);g.setColour(page ? juce::Colour(0xffb8707b) : juce::Colour(0xff6b6258));g.drawRoundedRectangle(track, height * .5f, 1);float s = height - 4, dx = button.getToggleState() ? track.getRight() - s - 2 : track.getX() + 2;g.setColour(page ? juce::Colour(0xffe2c8c4) : juce::Colour(0xffb8aa8d));g.fillEllipse(dx, track.getY() + 2, s, s);g.setColour(juce::Colour(0xff151416));g.drawEllipse(dx, track.getY() + 2, s, s, 1);g.setColour(cream);g.setFont(juce::Font(14.0f));g.drawText(button.getButtonText(), track.getRight() + 8, b.getY(), b.getWidth(), b.getHeight(), juce::Justification::centredLeft); }
private:
 static juce::Image loadKnob(int i) { switch (i) { case 0:return juce::ImageFileFormat::loadFrom(BinaryData::knob_01_png, BinaryData::knob_01_pngSize);case 1:return juce::ImageFileFormat::loadFrom(BinaryData::knob_02_png, BinaryData::knob_02_pngSize);case 2:return juce::ImageFileFormat::loadFrom(BinaryData::knob_03_png, BinaryData::knob_03_pngSize);case 3:return juce::ImageFileFormat::loadFrom(BinaryData::knob_04_png, BinaryData::knob_04_pngSize);case 4:return juce::ImageFileFormat::loadFrom(BinaryData::knob_05_png, BinaryData::knob_05_pngSize);case 5:return juce::ImageFileFormat::loadFrom(BinaryData::knob_06_png, BinaryData::knob_06_pngSize);case 6:return juce::ImageFileFormat::loadFrom(BinaryData::knob_07_png, BinaryData::knob_07_pngSize);case 7:return juce::ImageFileFormat::loadFrom(BinaryData::knob_08_png, BinaryData::knob_08_pngSize);default:return juce::ImageFileFormat::loadFrom(BinaryData::knob_09_png, BinaryData::knob_09_pngSize); } }
														 static juce::Image knobImageFor(const juce::Slider& s) { auto id = s.getComponentID();if (id == "distDrive" || id == "wowSpeed" || id == "reverbSize")return loadKnob(6);if (id == "distMix" || id == "chorusDepth" || id == "ghostMix")return loadKnob(2);if (id == "distCassette" || id == "flangerRate" || id == "squeezeMix")return loadKnob(4);if (id == "freqShiftHz" || id == "reverbCrossover" || id == "stutterRate")return loadKnob(0);if (id == "wowAmount" || id == "flangerDepth" || id == "driftAmount")return loadKnob(7);if (id == "chorusRate" || id == "reverbDamping" || id == "stutterLength")return loadKnob(1);if (id == "chorusMix" || id == "flangerFeedback" || id == "driftRate")return loadKnob(5);if (id == "flangerMix" || id == "reverbLowLevel" || id == "squeezeAmount")return loadKnob(3);return loadKnob(8); }
														 float pointerJitter = 0.0f, animationPhase = 0.0f;
};
inline const juce::Colour FreakLookAndFeel::mint{ 0xff1c2421 };inline const juce::Colour FreakLookAndFeel::cream{ 0xffd8caab };inline const juce::Colour FreakLookAndFeel::bezel{ 0xff0b0b0d };inline const juce::Colour FreakLookAndFeel::rust{ 0xff7a3038 };inline const juce::Colour FreakLookAndFeel::inkDark{ 0xff121114 };